version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=my_root_password
      - MARIADB_DATABASE=my_database_name
      - MARIADB_USER=my_database_user
      - MARIADB_PASSWORD=my_database_password
    ports:
      - "3306:3306"
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  
  moodle:
    image: 'bitnami/moodle:latest'
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=my_database_name
      - MOODLE_DATABASE_USER=my_database_user
      - MOODLE_DATABASE_PASSWORD=my_database_password
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin_password
      - MOODLE_EMAIL=admin@example.com
    volumes:
      - 'moodle_data:/bitnami/moodle'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
